-- MASTER SCHEMA: DENTALREACH ASTRO
-- Consolidates all legacy features + new requirements

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- CLEANUP (Reset for Import)
DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
DROP TRIGGER IF EXISTS update_articles_updated_at ON public.articles;
DROP TABLE IF EXISTS public.posts CASCADE;
DROP TABLE IF EXISTS public.threads CASCADE;
DROP TABLE IF EXISTS public.seo_settings CASCADE;
DROP TABLE IF EXISTS public.showcase_products CASCADE;
DROP TABLE IF EXISTS public.awards CASCADE;
DROP TABLE IF EXISTS public.listings CASCADE;
DROP TABLE IF EXISTS public.podcasts CASCADE;
DROP TABLE IF EXISTS public.jobs CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.articles CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS article_status CASCADE;
DROP TYPE IF EXISTS event_type CASCADE;
DROP TYPE IF EXISTS job_type_enum CASCADE;

-- Enums
CREATE TYPE user_role AS ENUM ('super_admin', 'admin', 'editor', 'author', 'dentist', 'student', 'business', 'member', 'professional', 'team', 'company');
CREATE TYPE article_status AS ENUM ('draft', 'under_review', 'published', 'archived');
CREATE TYPE event_type AS ENUM ('conference', 'webinar', 'workshop', 'seminar', 'networking', 'exhibition');
CREATE TYPE job_type_enum AS ENUM ('full_time', 'part_time', 'contract', 'locum', 'internship');

-- 1. PROFILES
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  email TEXT,
  username TEXT UNIQUE, -- Made nullable for legacy compat
  full_name TEXT,
  first_name TEXT,
  last_name TEXT,
  role user_role DEFAULT 'dentist',
  is_verified BOOLEAN DEFAULT false,
  subscription_tier TEXT DEFAULT 'free',
  avatar_url TEXT,
  bio TEXT,
  specialty TEXT,
  clinic_name TEXT,
  location TEXT,
  website_url TEXT,
  years_of_experience INTEGER,
  slug TEXT UNIQUE,
  wp_author_id INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles" ON public.profiles FOR SELECT USING (true);

-- 2. CATEGORIES
CREATE TABLE public.categories (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  parent_id INTEGER REFERENCES public.categories(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public categories" ON public.categories FOR SELECT USING (true);

-- 3. ARTICLES
CREATE TABLE public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT, -- Mixed HTML/JSON support
  status article_status DEFAULT 'draft',
  category TEXT, -- Legacy Text Support
  category_id INTEGER REFERENCES public.categories(id),
  author_id UUID REFERENCES public.profiles(id),
  is_scholarly BOOLEAN DEFAULT false,
  is_approved BOOLEAN DEFAULT true,
  is_featured BOOLEAN DEFAULT false,
  doi TEXT,
  citation_style TEXT DEFAULT 'APA',
  "references" JSONB DEFAULT '[]'::JSONB,
  image_url TEXT,
  gallery TEXT[],
  meta_title TEXT,
  meta_description TEXT,
  views_count INTEGER DEFAULT 0,
  likes_count INTEGER DEFAULT 0,
  published_at TIMESTAMPTZ,
  reading_time INTEGER,
  tags TEXT[],
  keywords TEXT[],
  abstract TEXT,
  methodology TEXT,
  conclusions TEXT,
  file_url TEXT,
  seo_keywords TEXT[],
  -- WordPress Migration Columns
  wp_post_id INTEGER,
  wp_guid TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public articles" ON public.articles FOR SELECT USING (true);

-- 4. EVENTS
CREATE TABLE public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  type event_type DEFAULT 'webinar',
  start_date TIMESTAMPTZ, -- Make nullable if legacy data is partial
  end_date TIMESTAMPTZ,
  date TIMESTAMPTZ, -- Legacy compat
  time TEXT,
  is_virtual BOOLEAN DEFAULT false,
  location TEXT,
  location_name TEXT, -- Alias
  registration_url TEXT,
  organizer_id UUID REFERENCES public.profiles(id),
  image_url TEXT,
  status TEXT DEFAULT 'upcoming',
  website TEXT,
  country TEXT,
  country_code TEXT,
  event_format TEXT,
  event_category TEXT,
  max_attendees INTEGER,
  price NUMERIC,
  registration_deadline TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public events" ON public.events FOR SELECT USING (true);

-- 5. JOB POSTINGS (Legacy Name)
CREATE TABLE public.jobs ( -- Internal name 'jobs', legacy was 'job_postings'
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  employer_id UUID REFERENCES public.profiles(id),
  posted_by UUID REFERENCES public.profiles(id), -- Legacy alias for employer_id
  title TEXT NOT NULL,
  slug TEXT UNIQUE,
  company_name TEXT NOT NULL,
  location TEXT NOT NULL,
  type TEXT, -- Simplifies ENUM issues
  salary_range TEXT,
  description JSONB, -- Or Text
  requirements TEXT[],
  benefits TEXT[],
  experience_level TEXT,
  apply_url TEXT,
  logo_url TEXT,
  is_active BOOLEAN DEFAULT true,
  expires_at TIMESTAMPTZ,
  application_deadline TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public jobs" ON public.jobs FOR SELECT USING (true);

-- 6. PODCASTS
CREATE TABLE public.podcasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    host_name TEXT,
    guest_names TEXT[],
    category TEXT,
    duration_minutes INTEGER,
    episode_number INTEGER,
    season_number INTEGER,
    spotify_url TEXT,
    image_url TEXT,
    is_approved BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    views_count INTEGER DEFAULT 0,
    likes_count INTEGER DEFAULT 0,
    user_id UUID REFERENCES public.profiles(id),
    slug TEXT UNIQUE,
    tags TEXT[],
    transcript TEXT,
    key_topics TEXT[],
    meta_title TEXT,
    meta_description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.podcasts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public podcasts" ON public.podcasts FOR SELECT USING (true);

-- 7. DIRECTORY / LISTINGS
CREATE TABLE public.listings (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  owner_id UUID REFERENCES public.profiles(id),
  business_name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  address_json JSONB,
  contact_email TEXT,
  contact_phone TEXT,
  website TEXT,
  type TEXT,
  amenities TEXT[],
  opening_hours JSONB,
  rating_avg NUMERIC(3,2) DEFAULT 0,
  is_verified BOOLEAN DEFAULT false,
  gallery TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public listings" ON public.listings FOR SELECT USING (true);

-- 8. AWARDS
CREATE TABLE public.awards (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    year INTEGER NOT NULL,
    status TEXT DEFAULT 'nominations_open',
    hero_image TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.awards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public awards" ON public.awards FOR SELECT USING (true);

-- 9. SHOWCASE PRODUCTS
CREATE TABLE public.showcase_products (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  endorsement TEXT,
  link TEXT,
  image TEXT,
  size TEXT DEFAULT 'standard',
  gradient TEXT DEFAULT 'from-gray-900/50 to-transparent',
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.showcase_products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public products" ON public.showcase_products FOR SELECT USING (true);

-- 10. SEO SETTINGS
CREATE TABLE public.seo_settings (
  id SERIAL PRIMARY KEY,
  page_slug VARCHAR(255) UNIQUE NOT NULL,
  meta_title VARCHAR(255),
  meta_description TEXT,
  meta_keywords TEXT[], 
  og_type VARCHAR(50) DEFAULT 'website',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.seo_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public seo" ON public.seo_settings FOR SELECT USING (true);

-- 11. FORUM (Threads/Posts)
CREATE TABLE public.threads (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE, 
  author_id UUID REFERENCES public.profiles(id),
  category TEXT NOT NULL,
  content JSONB, 
  view_count INTEGER DEFAULT 0,
  is_pinned BOOLEAN DEFAULT false,
  is_locked BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.threads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public threads" ON public.threads FOR SELECT USING (true);

CREATE TABLE public.posts (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  thread_id UUID REFERENCES public.threads(id) ON DELETE CASCADE NOT NULL,
  author_id UUID REFERENCES public.profiles(id),
  content JSONB NOT NULL,
  parent_id UUID REFERENCES public.posts(id), 
  is_deleted BOOLEAN DEFAULT false,
  is_accepted_answer BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public posts" ON public.posts FOR SELECT USING (true);

-- TRIGGERS
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_articles_updated_at BEFORE UPDATE ON public.articles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
