-- PARITY MIGRATION: Aligning with FINAL_MIGRATION.sql
-- This ensures all legacy columns and tables exist in the new system.

-- 1. SEO Settings (Missing in initial scope)
CREATE TABLE IF NOT EXISTS public.seo_settings (
  id SERIAL PRIMARY KEY,
  page_slug VARCHAR(255) UNIQUE NOT NULL,
  meta_title VARCHAR(255),
  meta_description TEXT,
  meta_keywords TEXT[], 
  og_type VARCHAR(50) DEFAULT 'website',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Products / Showcase (Legacy e-commerce features)
CREATE TABLE IF NOT EXISTS public.showcase_products (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  endorsement TEXT,
  link TEXT,
  image TEXT,
  size TEXT DEFAULT 'standard',
  gradient TEXT DEFAULT 'from-gray-900/50 to-transparent',
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Podcasts (Ensuring full compatibility)
-- My previous schema might have been too simple or non-existent for podcasts specific fields
CREATE TABLE IF NOT EXISTS public.podcasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    host_name TEXT,
    guest_names TEXT[],
    category TEXT,
    duration_minutes INTEGER,
    episode_number INTEGER,
    season_number INTEGER,
    spotify_url TEXT,
    image_url TEXT,
    is_approved BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    views_count INTEGER DEFAULT 0,
    likes_count INTEGER DEFAULT 0,
    user_id UUID REFERENCES public.profiles(id),
    slug TEXT UNIQUE,
    tags TEXT[],
    transcript TEXT,
    key_topics TEXT[],
    meta_title TEXT,
    meta_description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Event Enhancements (Legacy columns)
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS max_attendees INTEGER;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS price NUMERIC;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS event_format TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS country_code TEXT;

-- 5. Article Enhancements (Scholarly Specifics)
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS methodology TEXT;
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS conclusions TEXT;
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS reading_time INTEGER;
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS file_url TEXT;

-- 6. Profile Enhancements
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS years_of_experience INTEGER;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS clinic_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS website_url TEXT;

-- 7. Permissions
ALTER TABLE public.seo_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.showcase_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.podcasts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read seo" ON public.seo_settings FOR SELECT USING (true);
CREATE POLICY "Public read products" ON public.showcase_products FOR SELECT USING (true);
CREATE POLICY "Public read podcasts" ON public.podcasts FOR SELECT USING (true);
