-- 0010_guides_schema.sql
-- Guides System

CREATE TABLE IF NOT EXISTS public.guides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  image_url TEXT,
  author TEXT,
  pages INTEGER,
  file_size TEXT,
  download_link TEXT,
  download_count INTEGER DEFAULT 0,
  is_featured BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.guides ENABLE ROW LEVEL SECURITY;

-- Policies
-- Public Read: Everyone can view guides
CREATE POLICY "Public read guides" ON public.guides
    FOR SELECT USING (true);

-- Admin Full Access (assuming admin check in app logic or separate policy if verified via role)
-- For simplicity in this stack, we rely on the above or specific admin policies if needed.
-- Adding a generic admin policy just in case:
CREATE POLICY "Admins full access guides" ON public.guides
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'super_admin'))
    );
